apiVersion: apps/v1
kind: Deployment
metadata:
  name: egov-enc-service
  namespace: digit
  labels:
    app: egov-enc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egov-enc-service
  template:
    metadata:
      labels:
        app: egov-enc-service
    spec:
      containers:
        - name: egov-enc-service
          image: localhost:5000/egovio/egov-enc-service:v2.9.2-4a60f20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1234
          envFrom:
            - configMapRef:
                name: digit-common-env
            - secretRef:
                name: digit-db-credentials
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:otel:postgresql://postgres:5432/egov"
            - name: SERVER_PORT
              value: "1234"
            - name: MASTER_PASSWORD
              value: "asd@#$@$!132123"
            - name: MASTER_SALT
              value: qweasdzx
            - name: MASTER_INITIALVECTOR
              value: qweasdzxqwea
            - name: MASTER_PASSWORD_PROVIDER
              value: software
            - name: EGOV_MDMS_SEARCH_ENDPOINT
              value: /mdms-v2/v1/_search
            - name: STATE_LEVEL_TENANT_ID
              value: pg.citya
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx192m"
          resources:
            limits:
              memory: 300Mi
              cpu: "250m"
            requests:
              memory: 192Mi
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /egov-enc-service/actuator/health
              port: 1234
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /egov-enc-service/actuator/health
              port: 1234
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /egov-enc-service/actuator/health
              port: 1234
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: egov-enc-service
  namespace: digit
spec:
  selector:
    app: egov-enc-service
  ports:
    - port: 1234
      targetPort: 1234
