apiVersion: apps/v1
kind: Deployment
metadata:
  name: egov-hrms
  namespace: digit
  labels:
    app: egov-hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egov-hrms
  template:
    metadata:
      labels:
        app: egov-hrms
    spec:
      containers:
        - name: egov-hrms
          image: localhost:5000/egovio/egov-hrms:hrms-boundary-0a4e737
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8092
          envFrom:
            - configMapRef:
                name: digit-common-env
            - secretRef:
                name: digit-db-credentials
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/egov"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: employee-group1
            - name: SERVER_PORT
              value: "8092"
            - name: EGOV_IDGEN_HOST
              value: "http://egov-idgen:8088"
            - name: EGOV_USER_HOST
              value: "http://egov-user:8107"
            - name: EGOV_FILESTORE_HOST
              value: "http://egov-filestore:8083"
            - name: EGOV_LOCALIZATION_HOST
              value: "http://egov-localization:8096"
            - name: EGOV_BOUNDARY_HOST
              value: "http://boundary-service:8081"
            - name: EGOV_STATELEVEL_TENANT
              value: pg
            - name: HRMS_SYSTEM_USERNAME
              value: INTERNAL_USER
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx192m"
          resources:
            limits:
              memory: 256Mi
              cpu: "250m"
            requests:
              memory: 128Mi
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /egov-hrms/actuator/health
              port: 8092
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /egov-hrms/actuator/health
              port: 8092
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /egov-hrms/actuator/health
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: egov-hrms
  namespace: digit
spec:
  selector:
    app: egov-hrms
  ports:
    - port: 8092
      targetPort: 8092
