apiVersion: v1
kind: ConfigMap
metadata:
  name: digit-common-env
  namespace: digit
data:
  SPRING_DATASOURCE_USERNAME: egov
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "2"
  SPRING_FLYWAY_ENABLED: "false"
  FLYWAY_ENABLED: "false"
  KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
  SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
  KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG: redpanda:9092
  EGOV_MDMS_HOST: "http://egov-mdms-service:8094"
  EGOV_MDMS_SEARCH_ENDPOINT: /mdms-v2/v1/_search
  STATE_LEVEL_TENANT_ID: pg
  EGOV_STATE_LEVEL_TENANT_ID: pg
  OTEL_TRACES_EXPORTER: none
  OTEL_INSTRUMENTATION_JDBC_ENABLED: "false"
