apiVersion: v1
kind: Secret
metadata:
  name: digit-db-credentials
  namespace: digit
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: egov123
  DB_PASSWORD: egov123
  POSTGRES_PASSWORD: egov123
